import React, { createContext, ReactNode, useContext, useEffect, useState } from 'react';

type Language = 'EN' | 'AM';

const translations: Record<Language, Record<string, string>> = {
	EN: {
		'nav.services': 'Services',
		'nav.industries': 'Industries',
		'nav.careers': 'Careers',
		'nav.about': 'About',
		'nav.contact': 'Contact',
		'nav.getStarted': 'Get Started',
		'nav.initiate': 'Initiate Dialogue',
		'nav.explore': 'Explore',
		'nav.viewAll': 'View All',
		'hero.tag': 'Enterprise HR Infrastructure',
		'hero.h1.1': "Building Ethiopia's",
		'hero.h1.2': 'Next Workforce',
		'hero.h1.3': 'Infrastructure.',
		'hero.desc': 'Modern Workforce for Hire, Manage and Compliance in Ethiopia for Foreign Companies.',
		'hero.btn.start': 'Get Started',
		'hero.btn.book': 'Book a Consultation',
		'hero.recentPayroll': 'Recent Payroll',
		'hero.salary': 'Salary',
		'hero.base': 'Base',
		'hero.bonus': 'Bonus',
		'pricing.title1': 'Scalable pricing for',
		'pricing.title2': 'modern enterprises',
		'pricing.desc': 'Transform your workforce infrastructure with plans designed to scale from growing startups to continental enterprises.',
		'pricing.monthly': 'Monthly Billing',
		'pricing.annual': 'Annual Billing',
		'pricing.save': 'Save 20%',
		'pricing.mostPopular': 'Most Popular',
		'services.tag': 'Core Operations',
		'services.title': 'Enterprise Services Ecosystem',
		'metrics.title1': 'The Scale of',
		'metrics.title2': 'Our Impact',
		'metrics.f1.title': 'Workforce Scalability',
		'metrics.f1.desc': 'Navigate complex African labor frameworks with dynamically updated legal intelligence and automated regulatory reporting.',
		'metrics.f2.title': 'HR Automation',
		'metrics.f2.desc': 'Encrypted, on-continent data localization ensuring absolute compliance with regional data protection directives.',
		'metrics.f3.title': 'Compliance Systems',
		'metrics.f3.desc': 'Transform raw continental workforce data into actionable, board-level strategic insights and predictive modeling.',
		'services.payroll.title': 'Payroll \n Outsourcing',
		'services.payroll.desc':
			'Unify your entire African workforce under a single financial architecture. Automate multi-currency disbursements, localized tax withholdings, and statutory deductions with zero operational friction.',
		'services.payroll.btn': 'Explore Payroll Infrastructure',
		'services.recruitment.title': 'Recruitment \n & Staffing',
		'services.recruitment.desc':
			'Deploy advanced operational frameworks to map capabilities, track executive KPIs, and automate complex onboarding procedures across multiple subsidiaries and time zones.',
		'services.recruitment.feature1': 'Predictive modeling',
		'services.recruitment.feature2': 'Automated workflows',
		'services.hr.title': 'HR \n Outsourcing',
		'services.hr.desc':
			'Built for the demands of high-growth African enterprises. Our infrastructure provides the stability and robust API ecosystem required for rapid market penetration.',
		'services.hr.btn': 'Initiate Deployment',
		'testimonials.title': 'Trusted by \n Continental Leaders',
		'finalCta.title': 'Command your workforce with unparalleled precision.',
		'why.tag': 'Strategic Advantage',
		'why.title1': 'Why Foreign Companies',
		'why.title2': 'Choose',
		'why.desc':
			"We eliminate the friction of entering the Ethiopian market by providing an unshakeable operational foundation. Focus on your growth, we'll handle the ground reality.",
		'contact.title': 'Initiate Dialogue',
		'footer.rights': 'All rights reserved.',
		'servicesHero.system': 'System',
		'servicesHero.sysOp': 'SYS.OP.247 // ACTIVE',
		'servicesHero.scope': 'Scope',
		'servicesHero.scopeValue': 'Enterprise Workforce Operations',
		'servicesHero.workforce': 'WORKFORCE',
		'servicesHero.architecture': 'ARCHITECTURE',
		'servicesHero.description':
			'We do not provide standard HR services. We engineer, deploy, and manage the human capital infrastructure required for high-growth enterprises to scale without friction.',
		'servicesHero.deploySystems': 'Deploy Systems',
		'servicesEcosystem.title': 'The Operational Ecosystem',
		'servicesEcosystem.subtitle': 'Interact with the index below to explore our core enterprise deployments.',
		'servicesEcosystem.visualDataFeed': 'Visual Data Feed',
		'servicesEcosystem.hrOutsourcing.title': 'HR Outsourcing',
		'servicesEcosystem.hrOutsourcing.desc':
			'Comprehensive offloading of human capital management, ensuring complete enterprise compliance across multiple African jurisdictions.',
		'servicesEcosystem.hrOutsourcing.cta': 'Deploy HR Framework',
		'servicesEcosystem.recruitment.title': 'Recruitment & Staffing',
		'servicesEcosystem.recruitment.desc':
			'Precision executive search and massive volume staffing. We utilize algorithmic market analysis for exact target identification.',
		'servicesEcosystem.recruitment.cta': 'Initiate Talent Search',
		'servicesEcosystem.payroll.title': 'Payroll Operations',
		'servicesEcosystem.payroll.desc': 'Zero-error multi-currency payroll execution. A seamless financial shield guaranteeing absolute reliability and tax compliance.',
		'servicesEcosystem.payroll.cta': 'Execute Payroll Integration',
		'servicesEcosystem.callCenter.title': 'Call Center Solutions',
		'servicesEcosystem.callCenter.desc': 'Deploy fully managed omni-channel support hubs. We provide the real estate, the technology, and the trained personnel.',
		'servicesEcosystem.callCenter.cta': 'Establish Support Hub',
		'servicesEcosystem.workspace.title': 'Workspace Solutions',
		'servicesEcosystem.workspace.desc': 'Procuring and managing premium operational real estate tailored to the precise structural needs of your deployed workforce.',
		'servicesEcosystem.workspace.cta': 'Procure Enterprise Space',
		'servicesEcosystem.training.title': 'Corporate Training',
		'servicesEcosystem.training.desc': 'Premium spaces and cognitive frameworks engineered for supreme human performance and corporate innovation.',
		'servicesEcosystem.training.cta': 'Initiate Training Engagement',
		'servicesStrategy.title': 'System Advantages',
		'servicesStrategy.previousLabel': 'Previous advantage',
		'servicesStrategy.nextLabel': 'Next advantage',
		'servicesStrategy.point1.title': 'Focus on Your Core Business',
		'servicesStrategy.point1.desc': 'Spend your time on operations, sales, and growth—not HR paperwork.',
		'servicesStrategy.point2.title': 'Reduce Compliance Risks',
		'servicesStrategy.point2.desc': 'Stay aligned with Ethiopian labor regulations and employment requirements.',
		'servicesStrategy.point3.title': 'Lower Operating Costs',
		'servicesStrategy.point3.desc': 'Avoid the expense of building and maintaining a full internal HR department.',
		'servicesStrategy.point4.title': 'Scale Faster',
		'servicesStrategy.point4.desc': 'Hire and onboard employees quickly as your business grows.',
		'servicesIndustries.title1': 'Operational Sectors',
		'servicesIndustries.title2': 'Dominated',
		'servicesIndustries.subtitle': "Cross-industry expertise powering the continent's most demanding corporate sectors.",
		'servicesIndustries.activeDeployment': 'Active Deployment',
		'servicesIndustries.bankingFinance': 'Banking & Finance',
		'servicesIndustries.technology': 'Technology',
		'servicesIndustries.retailLogistics': 'Retail & Logistics',
		'servicesIndustries.manufacturing': 'Manufacturing',
		'servicesIndustries.telecom': 'Telecom',
		'servicesIndustries.healthcare': 'Healthcare',
		'servicesIndustries.government': 'Government',
		'servicesIndustries.oilGas': 'Oil & Gas',
		'servicesProcess.executionProtocol': 'Execution Protocol',
		'servicesProcess.title1': 'The Operational Flow',
		'servicesProcess.title2': 'Architecture',
		'servicesProcess.step1.title': 'Consultation & Architecture',
		'servicesProcess.step1.desc': 'Mapping the operational gaps and designing the human capital infrastructure.',
		'servicesProcess.step2.title': 'Talent Mapping',
		'servicesProcess.step2.desc': 'Algorithmic market analysis and executive target identification.',
		'servicesProcess.step3.title': 'Verification Protocol',
		'servicesProcess.step3.desc': 'Rigorous legal, credential, and behavioral vetting processes.',
		'servicesProcess.step4.title': 'System Deployment',
		'servicesProcess.step4.desc': 'Seamless integration of personnel, payroll, and compliance systems.',
		'servicesProcess.step5.title': 'Workforce Optimization',
		'servicesProcess.step5.desc': 'Continuous performance analytics and structural scaling.',
		'servicesMetrics.title1': 'Trust Measured',
		'servicesMetrics.title2': 'In Scale',
		'servicesMetrics.description':
			"True operational power is validated entirely by scale and precision. We support the human infrastructure behind the continent's most demanding corporate entities.",
		'servicesMetrics.metric1.label': 'Enterprise Clients',
		'servicesMetrics.metric2.label': 'Payroll Operations Processed',
		'servicesMetrics.metric3.label': 'Countries Served',
		'servicesMetrics.metric4.label': 'Workforce Placements',
		'servicesMetrics.metric5.label': 'Talent Retention Rate',
		'servicesMetrics.metric6.label': 'Avg. Executive Hiring Speed',
		'servicesCTA.finalStep': 'Final Step',
		'servicesCTA.title1': 'Build Smarter',
		'servicesCTA.title2': 'Operations',
		'servicesCTA.title3': 'With 247HR',
		'servicesCTA.button': 'Initiate Deployment',
		'careersHero.tag': 'Talent Ecosystem 2026',
		'careersHero.titleLine1': 'BUILD THE',
		'careersHero.titleLine2': 'FUTURE OF WORK',
		'careersHero.titleLine3': 'WITH US.',
		'careersHero.description':
			'Join the workforce infrastructure powering modern Africa. An elite environment engineered for ambitious thinkers, creative operators, and executive leaders.',
		'careersHero.scroll': 'Scroll',
		'careersCulture.sectionTag': 'Culture // 01',
		'careersCulture.title1': "WE DON'T DO",
		'careersCulture.title2': 'ORDINARY.',
		'careersCulture.description':
			'Our culture is built for the obsessed. We believe that an elite workforce requires an environment that challenges, elevates, and rigorously supports its people. Here, operational excellence is the baseline.',
		'careersCulture.value1Title': 'Radical Accountability',
		'careersCulture.value1Desc': 'Ownership at every layer of the matrix.',
		'careersCulture.value2Title': 'Creative Operations',
		'careersCulture.value2Desc': 'Solving rigid problems with fluid thinking.',
		'careersCulture.quote': 'The most magnetic thing a company can offer is the standard it refuses to compromise on.',
		'careersCulture.quoteAuthor': 'CEO Directive',
		'careersRoles.openRequisitions': 'Open Requisitions',
		'careersRoles.title1': 'STEP INTO',
		'careersRoles.title2': 'THE ARENA.',
		'careersRoles.location': 'Location',
		'careersRoles.type': 'Type',
		'careersStories.sectionTag': 'Executive Perspectives // 03',
		'careersStories.quote': "We don't manage processes. We engineer structural momentum for the entire continent.",
		'careersStories.profileName': 'Amara K.',
		'careersStories.profileTitle': 'Head of Talent Systems',
		'careersStories.profileAlt': 'Profile',
		'careersStories.imageAlt': 'Workspace Environment',
		'careersBenefits.title1': 'THE',
		'careersBenefits.title2': 'STANDARDS.',
		'careersBenefits.benefit1.title': 'Executive Trajectory',
		'careersBenefits.benefit1.desc': 'Rigorous mentorship and unfiltered exposure to multi-national operations, accelerating your career by years.',
		'careersBenefits.benefit2.title': 'Sovereign Flexibility',
		'careersBenefits.benefit2.desc': 'We measure impact, not presence. Fluid remote frameworks structured around pure operational output.',
		'careersBenefits.benefit3.title': 'Cognitive Capital',
		'careersBenefits.benefit3.desc': 'Uncapped budgets for continued learning, certifications, and global enterprise conferences.',
		'careersBenefits.benefit4.title': 'Holistic Architecture',
		'careersBenefits.benefit4.desc': 'Premium healthcare scaling to your family, comprehensive wellness stipends, and mandated reset periods.',
		'careersProcess.title': 'The Path In.',
		'careersProcess.step1': 'Application',
		'careersProcess.step2': 'Screening',
		'careersProcess.step3': 'Interview',
		'careersProcess.step4': 'Assessment',
		'careersProcess.step5': 'Offer',
		'careersProcess.step6': 'Onboarding',
		'jobs.common.fullTime': 'Full-Time',

		'jobs.vpOperations.title': 'VP of Enterprise Operations',
		'jobs.vpOperations.department': 'Executive Leadership',
		'jobs.vpOperations.location': 'Addis Ababa, Ethiopia / Hybrid',
		'jobs.vpOperations.experience': '10+ Years Enterprise',
		'jobs.vpOperations.compensation': 'Top 5% Market + Equity',
		'jobs.vpOperations.window': 'Closes Oct 15, 2026',
		'jobs.vpOperations.heroHeading': 'Lead the Future',
		'jobs.vpOperations.heroSubheading': 'of Workforce Innovation.',
		'jobs.vpOperations.storyHeading': 'A CATALYTIC',
		'jobs.vpOperations.storySubheading': 'LEADERSHIP OPPORTUNITY.',
		'jobs.vpOperations.storyParagraph1':
			'This is not a maintenance role. As the VP of Enterprise Operations, you will architect the foundational systems that drive our multi-national workforce strategies. You will inherit a robust infrastructure and be tasked with scaling it across emerging African markets, leveraging high-level operational intelligence and raw ambition.',
		'jobs.vpOperations.storyParagraph2':
			'You will have unfiltered exposure to our executive board, directly influencing how we deploy capital, restructure talent ecosystems, and outmaneuver traditional consulting constraints. We are looking for someone who thinks in decades but executes in days.',
		'jobs.vpOperations.responsibility1': 'Architect scalable operational frameworks that support 500+ elite personnel across 4 distinct regions.',
		'jobs.vpOperations.responsibility2': 'Directly manage a multi-million dollar capital allocation strategy focused on internal workforce infrastructure.',
		'jobs.vpOperations.responsibility3': 'Partner with the CEO to reverse-engineer competitor talent systems and construct superior, disruptive alternatives.',
		'jobs.vpOperations.responsibility4':
			'Lead the digital transformation of our internal communication, migrating from fragmented software to a unified 247HR proprietary system.',
		'jobs.vpOperations.responsibility5': 'Cultivate a high-performance culture by establishing ruthless but supportive benchmarks for middle management.',
		'jobs.vpOperations.qual1.title': '10+ Years Enterprise Experience',
		'jobs.vpOperations.qual1.desc':
			'A proven track record of managing large-scale operations in Tier-1 consulting, high-growth tech, or multi-national corporate environments.',
		'jobs.vpOperations.qual2.title': 'Strategic Financial Literacy',
		'jobs.vpOperations.qual2.desc': 'Deep understanding of P&L mechanics, capital allocation, and ROI modeling for human capital investments.',
		'jobs.vpOperations.qual3.title': 'African Market Fluency',
		'jobs.vpOperations.qual3.desc': 'Nuanced understanding of pan-African business ecosystems, regulatory environments, and high-value talent networks.',
		'jobs.vpOperations.qual4.title': 'Sovereign Execution',
		'jobs.vpOperations.qual4.desc': 'The ability to operate in highly ambiguous, high-pressure environments without needing a playbook. You write the playbook.',
		'jobs.workspaceArchitect.title': 'Senior Workspace Architect',
		'jobs.workspaceArchitect.department': 'Infrastructure Design',
		'jobs.workspaceArchitect.location': 'Lagos, Nigeria',
		'jobs.workspaceArchitect.experience': '7+ Years Spatial Design',
		'jobs.workspaceArchitect.compensation': 'Competitive + Performance Bonus',
		'jobs.workspaceArchitect.window': 'Closes Nov 1, 2026',
		'jobs.workspaceArchitect.heroHeading': 'Design the Core',
		'jobs.workspaceArchitect.heroSubheading': 'of Corporate Ecosystems.',
		'jobs.workspaceArchitect.storyHeading': 'SPATIAL',
		'jobs.workspaceArchitect.storySubheading': 'INTELLIGENCE MASTERED.',
		'jobs.workspaceArchitect.storyParagraph1':
			'Our physical and digital workspaces are the bedrock of our consulting philosophy. As our Senior Workspace Architect, your mandate is to conceptualize and execute next-generation office environments that foster intense focus and fluid collaboration.',
		'jobs.workspaceArchitect.storyParagraph2':
			'You will break away from stale corporate layouts. We demand bold, intelligent, deeply immersive spatial designs that reflect the energy of modern Africa while serving extreme functional requirements. Your work will dictate how our elite consultants operate on a daily basis.',
		'jobs.workspaceArchitect.responsibility1': 'Lead end-to-end design and execution of three major regional HQ rollouts across West Africa.',
		'jobs.workspaceArchitect.responsibility2': 'Integrate advanced IoT and environmental control systems seamlessly into bespoke physical infrastructure.',
		'jobs.workspaceArchitect.responsibility3': 'Negotiate and manage top-tier vendor relationships, ensuring uncompromising material quality and precise timelines.',
		'jobs.workspaceArchitect.responsibility4': "Develop a proprietary '247HR Spatial Identity Guide' to standardize future rapid-deploy offices.",
		'jobs.workspaceArchitect.qual1.title': '7+ Years Commercial Architecture',
		'jobs.workspaceArchitect.qual1.desc': 'Extensive background in spatial design or high-end corporate interiors with a focus on modern utility.',
		'jobs.workspaceArchitect.qual2.title': 'Advanced Software Expertise',
		'jobs.workspaceArchitect.qual2.desc':
			'Expertise in AutoCAD, Revit, and rendering engines (V-Ray, Lumion), combined with a brutalist yet luxurious aesthetic sensibility.',
		// Talent Analytics - EN Translations (MISSING - Add these)
		'jobs.talentAnalytics.title': 'Head of Talent Analytics',
		'jobs.talentAnalytics.department': 'Human Capital Strategy',
		'jobs.talentAnalytics.location': 'Remote / EMEA',
		'jobs.talentAnalytics.experience': '8+ Years Data Science / HR',
		'jobs.talentAnalytics.compensation': 'Top 10% Market + Equity',
		'jobs.talentAnalytics.window': 'Rolling Admission',
		'jobs.talentAnalytics.heroHeading': 'Quantify',
		'jobs.talentAnalytics.heroSubheading': 'Human Potential.',
		'jobs.talentAnalytics.storyHeading': 'PREDICTIVE',
		'jobs.talentAnalytics.storySubheading': 'TALENT MODELING.',
		'jobs.talentAnalytics.storyParagraph1':
			'Data is our ultimate lever. The Head of Talent Analytics will take ownership of our entire human capital data pipeline, transforming disjointed behavioral metrics into precise, actionable strategic directives for the executive team.',
		'jobs.talentAnalytics.storyParagraph2':
			"We don't do basic HR reporting. You will construct predictive models to anticipate burnout, optimize team assembly based on psychological profiles, and quantify the exact ROI of our talent acquisition channels. You will turn human behavior into competitive mathematical advantages.",
		'jobs.talentAnalytics.responsibility1': 'Build and deploy predictive attrition and performance models using advanced statistical techniques and machine learning.',
		'jobs.talentAnalytics.responsibility2': 'Design real-time executive dashboards that provide unfiltered visibility into global workforce health and dynamics.',
		'jobs.talentAnalytics.responsibility3': 'Audit and completely overhaul our performance review algorithms to eliminate bias and reward asymmetric impact.',
		'jobs.talentAnalytics.responsibility4': 'Collaborate directly with the VP of Enterprise Operations to model the financial impact of structural reorganizations.',
		'jobs.talentAnalytics.qual1.title': '8+ Years Data Science',
		'jobs.talentAnalytics.qual1.desc': 'Bridging data science and human capital, preferably within high-growth tech or elite consulting.',
		'jobs.talentAnalytics.qual2.title': 'Technical Mastery',
		'jobs.talentAnalytics.qual2.desc': 'Expert-level proficiency in Python, R, SQL, and advanced visualization platforms (Tableau, PowerBI).',
		'jobs.talentAnalytics.qual3.title': 'Executive Storytelling',
		'jobs.talentAnalytics.qual3.desc': 'Demonstrated ability to translate highly complex statistical findings into blunt, undeniable business cases.',
		'jobs.talentAnalytics.qual4.title': 'Analytical Skepticism',
		'jobs.talentAnalytics.qual4.desc': 'A deep skepticism of traditional HR metrics and a relentless drive to measure what actually dictates success.',
		'jobs.workspaceArchitect.qual3.title': 'High-Budget Management',
		'jobs.workspaceArchitect.qual3.desc': 'Track record of managing Br5M+ build-out budgets without sacrificing design integrity or missing milestones.',
		'jobs.workspaceArchitect.qual4.title': 'Environmental Psychology',
		'jobs.workspaceArchitect.qual4.desc': 'Deep understanding of how physical environments influence high-stakes professional performance and collaboration.',
		'jobs.complianceDirector.title': 'Director of Compliance Systems',
		'jobs.complianceDirector.department': 'Risk & Governance',
		'jobs.complianceDirector.location': 'Johannesburg, South Africa',
		'jobs.complianceDirector.experience': '12+ Years Governance',
		'jobs.complianceDirector.compensation': 'Highly Competitive',
		'jobs.complianceDirector.window': 'Closes Dec 1, 2026',
		'jobs.complianceDirector.heroHeading': 'Defend Our',
		'jobs.complianceDirector.heroSubheading': 'Aggressive Growth.',
		'jobs.complianceDirector.storyHeading': 'FORTIFIED',
		'jobs.complianceDirector.storySubheading': 'GOVERNANCE.',
		'jobs.complianceDirector.storyParagraph1':
			'Scaling across diverse African markets requires navigating an incredibly complex web of regulatory frameworks. The Director of Compliance Systems is the shield that allows our operations to move with aggressive speed without triggering existential risk.',
		'jobs.complianceDirector.storyParagraph2':
			'You will not merely react to regulations; you will anticipate them. Your role is to build an automated, impenetrable compliance infrastructure that seamlessly integrates into our daily operations. You will turn regulatory adherence from a bureaucratic roadblock into a silent, frictionless guarantee.',
		'jobs.complianceDirector.responsibility1':
			'Architect a pan-African compliance engine covering labor laws, data privacy (GDPR/POPIA), and financial reporting standards.',
		'jobs.complianceDirector.responsibility2': 'Lead cross-border internal audits and serve as the primary liaison with top-tier external legal counsel and regulators.',
		'jobs.complianceDirector.responsibility3': 'Automate 80% of routine compliance checks by integrating specialized software directly into our HR and finance stacks.',
		'jobs.complianceDirector.responsibility4': 'Develop rapid-response protocols for regulatory shifts, ensuring zero operational downtime in volatile jurisdictions.',
		'jobs.complianceDirector.qual1.title': '12+ Years Corporate Governance',
		'jobs.complianceDirector.qual1.desc': 'Extensive background in risk management or corporate law, with a massive focus on multi-jurisdictional compliance.',
		'jobs.complianceDirector.qual2.title': 'Pan-African Legal Frameworks',
		'jobs.complianceDirector.qual2.desc': 'Deep, battle-tested knowledge of labor laws and data privacy regulations across key African hubs (SA, Kenya, Nigeria).',
		'jobs.complianceDirector.qual3.title': 'Digital Transformation Leadership',
		'jobs.complianceDirector.qual3.desc': 'Experience leading digital transformations within legal or compliance departments, moving from paper to automated systems.',
		'jobs.complianceDirector.qual4.title': 'Unshakeable Risk Assessment',
		'jobs.complianceDirector.qual4.desc': 'An unflappable demeanor with the ability to make definitive, high-stakes risk assessments under extreme operational pressure.',
		'careersWorkspace.sectionTag': 'Operational Ecosystem // 05',
		'careersWorkspace.title': 'THE ARCHITECTURE \n OF AMBITION.',
		'careersWorkspace.label1': 'HQ / Collaborative Core',
		'careersWorkspace.label2': 'Executive Lounge',
		'careersWorkspace.imageAlt1': 'Luxury Workspace',
		'careersWorkspace.imageAlt2': 'Lounge',
		'careersWorkspace.description':
			'Spaces designed not just to house personnel, but to physically catalyze elite performance. The 247HR workspace acts as a luxury asset, fostering high-level focus and collaborative synthesis.',
		'careersCTA.backgroundAlt': 'Abstract Cinematic',
		'careersCTA.title1': 'JOIN THE WORKFORCE BUILDING THE FUTURE OF',
		'careersCTA.title2': 'ENTERPRISE OPERATIONS.',
		'careersCTA.button': 'Initiate Application',
		'aboutHero.tagline': 'The Future Operating System',
		'aboutHero.title1': 'Powering the',
		'aboutHero.title2': 'Workforce Behind',
		'aboutHero.title3': "Africa's Leading Enterprises",
		'aboutHero.description':
			'We are the operational backbone of modern workforce ecosystems, architecting scalable human capital infrastructure for rapid market penetration.',
		'aboutHero.buttonExplore': 'Explore Services',
		'aboutHero.buttonWorkWithUs': 'Work With Us',
		'aboutHero.imageAlt': 'Enterprise Environment',
		'aboutHero.metric1Title': 'Operational Velocity',
		'aboutHero.metric1Value': '+24% MoM',
		'aboutHero.metric2Title': 'Active Deployments',
		'aboutHero.metric2Value': '14 Jurisdictions',
		'aboutHero.metric2Extra': '+1.2k',
		'aboutStory.mainImageAlt': '247HR Team Operations',
		'aboutStory.overlayImageAlt': 'Professional Working',
		'aboutStory.title1': 'Architecting the',
		'aboutStory.title2': 'Continental Engine',
		'aboutStory.section1Title': 'The Founding Vision',
		'aboutStory.section1Desc':
			'Established with a singular directive: to remove the friction from pan-African enterprise expansion. We saw high-growth companies bottlenecked not by market demand, but by fragmented human capital infrastructure.',
		'aboutStory.section2Title': 'Operational Growth',
		'aboutStory.section2Desc':
			'What began as a premium recruitment consultancy has aggressively scaled into a comprehensive workforce operating system. We now engineer everything from multi-jurisdictional payroll to executive talent orchestration.',
		'aboutStory.quote': '"Our mandate isn\'t just staffing. It\'s building the resilient operational architecture that allows businesses to scale fearlessly."',
		'aboutMission.missionLabel': 'Our Mission',
		'aboutMission.missionTitle1': 'To engineer the most',
		'aboutMission.missionTitle2': 'resilient',
		'aboutMission.missionTitle3': "human capital systems for Africa's high-growth enterprises.",
		'aboutMission.missionDesc':
			'We deploy world-class workforce infrastructure that eliminates operational friction, ensuring our clients can focus strictly on market domination while we handle the complexity of talent, compliance, and scale.',
		'aboutMission.visionLabel': 'Our Vision',
		'aboutMission.visionTitle1': 'To become the',
		'aboutMission.visionTitle2': 'default operating system',
		'aboutMission.visionTitle3': 'for continental workforce management.',
		'aboutMission.visionDesc':
			'We envision a borderless corporate landscape where deploying talent across African jurisdictions is as seamless, transparent, and secure as processing a digital payment.',
		'aboutValues.title1': 'The Code We',
		'aboutValues.title2': 'Operate By',
		'aboutValues.description':
			"Our core values aren't posters on a wall; they are the strict operational protocols that govern every deployment, recruitment, and strategy we execute.",
		'aboutValues.value1.title': 'Operational Excellence',
		'aboutValues.value1.desc': 'Precision in every process, from compliance to payroll execution.',
		'aboutValues.value2.title': 'Talent Intelligence',
		'aboutValues.value2.desc': 'Data-driven recruitment replacing guesswork with strategic acquisition.',
		'aboutValues.value3.title': 'Speed',
		'aboutValues.value3.desc': 'Unmatched velocity in deployment and operational scaling.',
		'aboutValues.value4.title': 'Enterprise Reliability',
		'aboutValues.value4.desc': 'A robust infrastructure that never fails when it matters most.',
		'aboutValues.value5.title': 'Workforce Innovation',
		'aboutValues.value5.desc': 'Constantly pushing the boundaries of human capital technology.',
		'aboutValues.value6.title': 'Integrity',
		'aboutValues.value6.desc': 'Absolute transparency and uncompromising ethical standards.',
		'aboutTeam.title1': 'Command &',
		'aboutTeam.title2': 'Control',
		'aboutTeam.description': 'A leadership team forged in the complexities of continental expansion. We bring decades of multi-jurisdictional enterprise experience.',
		'aboutTeam.button': 'View Full Leadership',
		'aboutTeam.leader1.name': 'David O. Alabi',
		'aboutTeam.leader1.role': 'Chief Executive Officer',
		'aboutTeam.leader2.name': 'Aisha N. Mensah',
		'aboutTeam.leader2.role': 'Head of Talent Intelligence',
		'aboutTeam.leader3.name': 'Samuel K. Tesfaye',
		'aboutTeam.leader3.role': 'VP of Enterprise Operations',
		'aboutMetrics.title1': 'The Scale of',
		'aboutMetrics.title2': 'Our Impact',
		'aboutMetrics.description':
			"We do not deal in assumptions. We deal in measurable, scalable enterprise performance. Our infrastructure supports the workforce demands of the continent's most ambitious companies.",
		'aboutMetrics.metric1.label': 'Enterprise Clients',
		'aboutMetrics.metric1.desc': 'across 14 active jurisdictions',
		'aboutMetrics.metric2.label': 'Workforce Placements',
		'aboutMetrics.metric2.desc': 'talent orchestrated annually',
		'aboutMetrics.metric3.label': 'Payroll Operations',
		'aboutMetrics.metric3.desc': 'processed through our architecture',
		'aboutMetrics.metric4.label': 'Talent Success Rate',
		'aboutMetrics.metric4.desc': 'executive & technical retention',
		'aboutCulture.title1': 'A Culture of',
		'aboutCulture.title2': 'Relentless Execution',
		'aboutCulture.description': 'Behind our technology lies a team of operators who believe that human capital is the ultimate competitive advantage.',
		'aboutCulture.quote': '"We don\'t just hire talent. We architect teams."',
		'aboutCulture.quoteAuthor': 'Head of Internal Operations',
		'aboutCulture.imageAlt1': 'Team Collaboration',
		'aboutCulture.imageAlt2': 'Leadership Moment',
		'aboutCulture.imageAlt3': 'Modern Office Corporate Building',
		'aboutCTA.badge': 'The Next Step',
		'aboutCTA.title1': 'Build the Future of',
		'aboutCTA.title2': 'Workforce Operations',
		'aboutCTA.title3': 'With 247HR',
		'aboutCTA.buttonPrimary': 'Start Your Transformation',
		'aboutCTA.buttonSecondary': 'Speak to Leadership',
		// Hero Section
		'contact.heroBadge': 'Global Communications',
		'contact.heroTitle1': "Let's Build",
		'contact.heroTitle2': 'Smarter Workforce',
		'contact.heroTitle3': 'Systems Together.',
		'contact.heroDescription': "Connect with the future of enterprise workforce solutions. We don't do standard support, we provide elite operational consultation.",

		// Form Section
		'contact.formTitle': 'Initiate Dialogue',
		'contact.fullNamePlaceholder': 'Full Name',
		'contact.companyNamePlaceholder': 'Company Name',
		'contact.emailPlaceholder': 'Email Address',
		'contact.phonePlaceholder': 'Phone Number',
		'contact.serviceInterestPlaceholder': 'Service Interest',
		'contact.serviceOption1': 'Executive Search',
		'contact.serviceOption2': 'Workforce Infrastructure',
		'contact.serviceOption3': 'Risk & Compliance',
		'contact.serviceOption4': 'Talent Analytics',
		'contact.messagePlaceholder': 'Message',
		'contact.submitButton': 'Initiate Dialogue',

		// Contact Information
		'contact.hqLabel': 'Global HQ',
		'contact.hqAddress1': 'The Exchange Tower,',
		'contact.hqAddress2': 'Addis Ababa, Ethiopia',
		'contact.hqAddress3': ' ',
		'contact.emailLabel': 'Direct Line',
		'contact.emailAddress': 'executive@247consulting.com',
		'contact.phoneLabel': 'Operations Center',
		'contact.phoneNumber': '+254 700 247 000',
		'contact.coverageLabel': 'Global Coverage',
		'contact.coverageLine1': '24/7 Enterprise Support',
		'contact.coverageLine2': 'GMT+3 Primary Operations',

		// Map Section
		'contact.mapHubName': 'Nairobi Hub',
		'contact.mapCoordinates': '1.2921° S, 36.8219° E',

		// Final CTA Section
		'contact.finalBadge': 'Executive Calendar Open',
		'contact.finalTitle1': 'Start Building The Future',
		'contact.finalTitle2': 'Of Workforce Operations',
		'contact.finalButton': 'Schedule Strategy Session',
		// Footer CTA Section
		'footer.ctaTitle1': 'THE APEX',
		'footer.ctaTitle2': 'OF ENTERPRISE HR.',
		'footer.ctaButton': 'Initiate Dialogue',
		'footer.newsletterText': 'Sign up for exclusive intelligence on pan-African workforce architecture.',
		'footer.newsletterPlaceholder': 'Executive Email',

		// Footer HQ Section
		'footer.hqDescription': 'Global Headquarters: Nairobi, Kenya. Deploying elite workforce infrastructure across emerging enterprise markets.',

		// Footer Column Titles
		'footer.intelligenceTitle': 'Intelligence',
		'footer.infrastructureTitle': 'Infrastructure',
		'footer.networkTitle': 'Network',

		// Intelligence Links
		'footer.aboutBoard': 'About Board',
		'footer.leadership': 'Leadership',
		'footer.globalNetwork': 'Global Network',
		'footer.esgImpact': 'ESG Impact',

		// Infrastructure Links
		'footer.executiveSearch': 'Executive Search',
		'footer.workforceOperations': 'Workforce Operations',
		'footer.talentAnalytics': 'Talent Analytics',
		'footer.riskCompliance': 'Risk & Compliance',

		// Network Links
		'footer.openRequisitions': 'Open Requisitions',
		'footer.lifeAt247hr': 'Life at 247HR',
		'footer.globalLocations': 'Global Locations',
		'footer.pressMedia': 'Press & Media',

		// Legal Links
		'footer.privacyProtocol': 'Privacy Protocol',
		'footer.termsOfService': 'Terms of Service',
		'footer.cookieArchitecture': 'Cookie Architecture',
	},
	AM: {
		'nav.services': 'አገልግሎቶች',
		'nav.industries': 'ኢንዱስትሪዎች',
		'nav.careers': 'ስራዎች',
		'nav.about': 'ስለ እኛ',
		'nav.contact': 'ያግኙን',
		'nav.getStarted': 'ይጀምሩ',
		'nav.initiate': 'ውይይት ይጀምሩ',
		'nav.explore': 'ያስሱ',
		'nav.viewAll': 'ሁሉንም ይመልከቱ',
		'hero.tag': 'የኢንተርፕራይዝ የሰው ሀይል መሠረተ ልማት',
		'hero.h1.1': 'የኢትዮጵያን',
		'hero.h1.2': 'ቀጣይ የሰው ሀይል',
		'hero.h1.3': 'መሠረተ ልማት እንገነባለን።',
		'hero.desc': 'ለውጭ ኩባንያዎች በኢትዮጵያ ውስጥ ዘመናዊ የሰው ሀይል ቅጥር፣ አስተዳደር እና ህግ አክባሪነት።',
		'hero.btn.start': 'ይጀምሩ',
		'hero.btn.book': 'ምክክር ይያዙ',
		'hero.recentPayroll': 'የቅርብ ጊዜ ክፍያ',
		'hero.salary': 'ደመወዝ',
		'hero.base': 'መሠረታዊ',
		'hero.bonus': 'ጉርሻ',
		'pricing.title1': 'ሊሰፋ የሚችል ዋጋ ለ',
		'pricing.title2': 'ዘመናዊ ኢንተርፕራይዞች',
		'pricing.desc': 'ከሚያድጉ ጀማሪዎች እስከ አህጉራዊ ኢንተርፕራይዞች በሚመጥን የዋጋ ዕቅዶች የሰው ሀይልዎን መሠረተ ልማት ይቀይሩ።',
		'pricing.monthly': 'ወርሃዊ ክፍያ',
		'pricing.annual': 'አመታዊ ክፍያ',
		'pricing.save': '20% ይቆጥቡ',
		'pricing.mostPopular': 'በጣም ታዋቂ',
		'services.tag': 'ዋና ተግባራት',
		'services.title': 'የኢንተርፕራይዝ አገልግሎት ስነ-ምህዳር',
		'metrics.title1': 'የተፅእኖአችን',
		'metrics.title2': 'ልኬት',
		'metrics.f1.title': 'የሰው ሀይል መስፋፋት',
		'metrics.f1.desc': 'የተወሳሰቡ የአፍሪካ የስራ ማዕቀፎችን በሚሻሻል ህጋዊ መረጃ እና አውቶማቲክ የቁጥጥር ሪፖርት ማሰስ።',
		'metrics.f2.title': 'የሰው ሀይል አውቶሜሽን',
		'metrics.f2.desc': 'የተመሰጠረ መረጃን በአህጉሪቱ ላይ ማከማቸት ከክልላዊ የመረጃ ጥበቃ መመሪያዎች ጋር ሙሉ በሙሉ መከበሩን ያረጋግጣል።',
		'metrics.f3.title': 'የህግ አክባሪነት ስርዓቶች',
		'metrics.f3.desc': 'ያልተቀነባበረ አህጉራዊ የሰው ሀይል መረጃን ወደ ተግባራዊ እና ስልታዊ ግንዛቤዎች እና ትንበያ ሞዴሎች ይቀይሩ።',
		'services.payroll.title': 'የክፍያ \n ውጭ አገልግሎት',
		'services.payroll.desc': 'መላውን የአፍሪካ የሰው ሀይልዎን በአንድ የፋይናንስ መዋቅር ስር ያዋህዱ። የባለብዙ ምንዛሪ ክፍያዎችን፣ ታክስን እና ህጋዊ ቅናሾችን ያለ ምንም የአሰራር ችግር ያውቶማቲክ ያድርጉ።',
		'services.payroll.btn': 'የክፍያ መሠረተ ልማትን ያስሱ',
		'services.recruitment.title': 'ቅጥር እና \n የሰው ሀይል',
		'services.recruitment.desc': 'አቅምን ለመለየት፣ የተግባር አመላካቾችን (KPIs) ለመከታተል እና ውስብስብ የቅጥር ሂደቶችን በተለያዩ ቅርንጫፎች እና የሰዓት ዞኖች ውስጥ አውቶማቲክ ለማድረግ የላቁ አሰራሮችን ይጠቀሙ።',
		'services.recruitment.feature1': 'ትንበያ ሞዴል',
		'services.recruitment.feature2': 'አውቶማቲክ የስራ ፍሰቶች',
		'services.hr.title': 'የሰው ሀይል \n ውጭ አገልግሎት',
		'services.hr.desc': 'በከፍተኛ ፍጥነት ለሚያድጉ የአፍሪካ ኢንተርፕራይዞች ፍላጎት የተገነባ። የእኛ መሠረተ ልማት ለፈጣን የገበያ ዘልቆ መግባት የሚያስፈልገውን መረጋጋት እና ጠንካራ የኤፒአይ (API) ስነ-ምህዳር ይሰጣል።',
		'services.hr.btn': 'ማሰማራት ይጀምሩ',
		'testimonials.title': 'በአህጉራዊ \n መሪዎች የታመነ',
		'finalCta.title': 'የሰው ሀይልዎን ወደር በሌለው ትክክለኛነት ያስተዳድሩ።',
		'why.tag': 'ስልታዊ ጠቀሜታ',
		'why.title1': 'ለምን የውጭ ኩባንያዎች',
		'why.title2': 'ይመርጣሉ',
		'why.desc': 'የማይናወጥ የአሰራር መሰረት በመስጠት ወደ ኢትዮጵያ ገበያ የመግባት ችግርን እናስወግዳለን። በእድገትዎ ላይ ያተኩሩ፣ እኛ የመሬት ላይ እውነታውን እናስተዳድራለን።',
		'contact.title': 'ውይይት ይጀምሩ',
		'footer.rights': 'መብቱ በህግ የተጠበቀ ነው።',
		'servicesHero.system': 'ስርዓት',
		'servicesHero.sysOp': 'ሲስ.ኦፕ.247 // ንቁ',
		'servicesHero.scope': 'ወሰን',
		'servicesHero.scopeValue': 'የኢንተርፕራይዝ የሰው ሀይል ስራዎች',
		'servicesHero.workforce': 'የሰው ሀይል',
		'servicesHero.architecture': 'ሥነ ህንጻ',
		'servicesHero.description': 'መደበኛ የሰው ሀይል አገልግሎቶችን አንሰጥም። ከፍተኛ እድገት ላላቸው ኢንተርፕራይዞች ያለምንም ችግር እንዲስፋፉ የሚያስችላቸውን የሰው ካፒታል መሠረተ ልማት እንመራለን፣ እናሰማራለን እንዲሁም እንቆጣጠራለን።',
		'servicesHero.deploySystems': 'ስርዓቶችን አሰማራ',
		'servicesEcosystem.title': 'የኦፕሬሽን ስነ-ምህዳር',
		'servicesEcosystem.subtitle': 'ዋና የኢንተርፕራይዝ ማሰማሪያዎቻችንን ለማሰስ ከታች ባለው መረጃ ጠቋሚ ላይ ይጫኑ።',
		'servicesEcosystem.visualDataFeed': 'የእይታ መረጃ ማቀርቢያ',
		'servicesEcosystem.hrOutsourcing.title': 'የሰው ሀይል ውጭ አገልግሎት',
		'servicesEcosystem.hrOutsourcing.desc': 'የሰው ካፒታል አስተዳደርን ሙሉ በሙሉ ማስተላለፍ፣ በበርካታ የአፍሪካ ግዛቶች ውስጥ ሙሉ የኢንተርፕራይዝ ታዛዥነትን ማረጋገጥ።',
		'servicesEcosystem.hrOutsourcing.cta': 'የሰው ሀይል ማዕቀፍ አሰማራ',
		'servicesEcosystem.recruitment.title': 'ቅጥር እና የሰው ሀይል አቅርቦት',
		'servicesEcosystem.recruitment.desc': 'ትክክለኛ የስራ ኃላፊ ፍለጋ እና ከፍተኛ መጠን ያለው የሰው ሀይል አቅርቦት። ትክክለኛ ዒላማ መለየት ለማድረግ አልጎሪዝሚክ የገበያ ትንተና እንጠቀማለን።',
		'servicesEcosystem.recruitment.cta': 'የተሰጥኦ ፍለጋ ይጀምሩ',
		'servicesEcosystem.payroll.title': 'የደመወዝ ክፍያ ስራዎች',
		'servicesEcosystem.payroll.desc': 'ስህተት የሌለው የባለብዙ ምንዛሪ የደመወዝ ክፍያ አፈጻጸም። ፍጹም አስተማማኝነት እና የግብር ታዛዥነት ዋስትና የሚሰጥ እንከን የለሽ የፋይናንስ ጋሻ።',
		'servicesEcosystem.payroll.cta': 'የደመወዝ ውህደት አስፈጽም',
		'servicesEcosystem.callCenter.title': 'የመጠይቅ ማእከል መፍትሄዎች',
		'servicesEcosystem.callCenter.desc': 'ሙሉ በሙሉ የሚተዳደሩ ባለብዙ መስመር የድጋፍ ማዕከላትን አሰማሩ። እኛ ሪል እስቴቱን፣ ቴክኖሎጂውን እና የሰለጠነ ሰው ሀይል እናቀርባለን።',
		'servicesEcosystem.callCenter.cta': 'የድጋፍ ማዕከል ይመስርቱ',
		'servicesEcosystem.workspace.title': 'የስራ ቦታ መፍትሄዎች',
		'servicesEcosystem.workspace.desc': 'ለተሰማራ የሰው ሀይልዎ ትክክለኛ መዋቅራዊ ፍላጎቶች የተበጀ ጥራት ያለው የስራ ሪል እስቴት ግዢ እና አስተዳደር።',
		'servicesEcosystem.workspace.cta': 'የኢንተርፕራይዝ ቦታ ይግዙ',
		'servicesEcosystem.training.title': 'የኮርፖሬት ስልጠና',
		'servicesEcosystem.training.desc': 'ከፍተኛ የሰው አፈጻጸም እና የኮርፖሬት ፈጠራ የተገነቡ ጥራት ያላቸው ቦታዎች እና የእውቀት ማዕቀፎች።',
		'servicesEcosystem.training.cta': 'የስልጠና ተሳትፎ ይጀምሩ',
		'servicesStrategy.title': 'የስርዓት ጥቅሞች',
		'servicesStrategy.previousLabel': 'ቀዳሚ ጥቅም',
		'servicesStrategy.nextLabel': 'ቀጣይ ጥቅም',
		'servicesStrategy.point1.title': 'በዋና ስራዎ ላይ ያተኩሩ',
		'servicesStrategy.point1.desc': 'ጊዜዎን በስራ ክንውኖች፣ ሽያጭ እና እድገት ላይ ያሳልፉ - እንጂ በሰው ሀይል ወረቀት ስራ ላይ አይደለም።',
		'servicesStrategy.point2.title': 'የታዛዥነት ስጋቶችን ይቀንሱ',
		'servicesStrategy.point2.desc': 'ከኢትዮጵያ የስራ ህጎች እና የቅጥር መስፈርቶች ጋር ተስማምተው ይቆዩ።',
		'servicesStrategy.point3.title': 'የስራ ማስኬጃ ወጪዎችን ይቀንሱ',
		'servicesStrategy.point3.desc': 'ሙሉ የውስጥ የሰው ሀይል ክፍል ከመገንባት እና ከማስኬድ ወጪ ይቆጠቡ።',
		'servicesStrategy.point4.title': 'በፍጥነት ያስፋፉ',
		'servicesStrategy.point4.desc': 'ንግድዎ እያደገ ሲሄድ ሰራተኞችን በፍጥነት ቅጥር እና አሰማራ ያድርጉ።',
		'servicesIndustries.title1': 'የኦፕሬሽን ዘርፎች',
		'servicesIndustries.title2': 'የተቆጣጠርነው',
		'servicesIndustries.subtitle': 'በአህጉሪቱ በጣም ፈላጊ የሆኑ የኮርፖሬት ዘርፎችን የሚያጎለብት የተለያየ ኢንዱስትሪ እውቀት።',
		'servicesIndustries.activeDeployment': 'ንቁ ማሰማራት',
		'servicesIndustries.bankingFinance': 'ባንክ እና ፋይናንስ',
		'servicesIndustries.technology': 'ቴክኖሎጂ',
		'servicesIndustries.retailLogistics': 'ችርቻሮ እና ሎጅስቲክስ',
		'servicesIndustries.manufacturing': 'ማኑፋክቸሪንግ',
		'servicesIndustries.telecom': 'ቴሌኮም',
		'servicesIndustries.healthcare': 'ጤና እንክብካቤ',
		'servicesIndustries.government': 'መንግስት',
		'servicesIndustries.oilGas': 'ነዳጅ እና ጋዝ',
		'servicesProcess.executionProtocol': 'የአፈጻጸም ፕሮቶኮል',
		'servicesProcess.title1': 'የኦፕሬሽን ፍሰት',
		'servicesProcess.title2': 'ሥነ ህንጻ',
		'servicesProcess.step1.title': 'ማማከር እና ሥነ ህንጻ',
		'servicesProcess.step1.desc': 'የኦፕሬሽን ክፍተቶችን መለየት እና የሰው ካፒታል መሠረተ ልማት ዲዛይን ማድረግ።',
		'servicesProcess.step2.title': 'ተሰጥኦ ካርታ',
		'servicesProcess.step2.desc': 'አልጎሪዝሚክ የገበያ ትንተና እና የስራ ኃላፊ ዒላማ መለየት።',
		'servicesProcess.step3.title': 'ማረጋገጫ ፕሮቶኮል',
		'servicesProcess.step3.desc': 'ጥብቅ ህጋዊ፣ ማስረጃ እና ባህሪ ማጣራት ሂደቶች።',
		'servicesProcess.step4.title': 'ስርዓት ማሰማራት',
		'servicesProcess.step4.desc': 'የሰራተኞች፣ የደመወዝ ክፍያ እና የህግ አክባሪነት ስርዓቶች እንከን የለሽ ውህደት።',
		'servicesProcess.step5.title': 'የሰው ሀይል ማመቻቸት',
		'servicesProcess.step5.desc': 'ቀጣይነት ያለው የአፈጻጸም ትንታኔ እና መዋቅራዊ መስፋፋት።',
		'servicesMetrics.title1': 'የሚታመንበት መጠን',
		'servicesMetrics.title2': 'በልኬት',
		'servicesMetrics.description': 'እውነተኛ የኦፕሬሽን ኃይል ሙሉ በሙሉ በልኬት እና በትክክለኛነት የሚረጋገጥ ነው። በአህጉሪቱ በጣም ፈላጊ ከሆኑ የኮርፖሬት ድርጅቶች በስተጀርባ ያለውን የሰው መሠረተ ልማት እንደግፋለን።',
		'servicesMetrics.metric1.label': 'የኢንተርፕራይዝ ደንበኞች',
		'servicesMetrics.metric2.label': 'የተከናወኑ የደመወዝ ክፍያ ስራዎች',
		'servicesMetrics.metric3.label': 'አገልግሎት የተሰጠባቸው አገሮች',
		'servicesMetrics.metric4.label': 'የሰው ሀይል ምደባዎች',
		'servicesMetrics.metric5.label': 'ተሰጥኦ ማቆየት መጠን',
		'servicesMetrics.metric6.label': 'አማካይ የስራ ኃላፊ ቅጥር ፍጥነት',
		'servicesCTA.finalStep': 'የመጨረሻ እርምጃ',
		'servicesCTA.title1': 'ብልህ ኦፕሬሽኖችን',
		'servicesCTA.title2': 'ኦፕሬሽኖች',
		'servicesCTA.title3': 'ከ247HR ጋር ይገንቡ',
		'servicesCTA.button': 'ማሰማራት ይጀምሩ',
		'careersHero.tag': 'የተሰጥኦ ስነ-ምህዳር 2026',
		'careersHero.titleLine1': 'የስራውን',
		'careersHero.titleLine2': 'የወደፊት ጊዜ ይገንቡ',
		'careersHero.titleLine3': 'ከእኛ ጋር።',
		'careersHero.description': 'ዘመናዊ አፍሪካን የሚያጎለብት የሰው ሀይል መሠረተ ልማትን ይቀላቀሉ። ለምኞተኞች አሳቢዎች፣ ፈጠራ ባለቤቶች እና ስራ አስፈጻሚ መሪዎች የተሰራ ልሂቃን ምህዳር።',
		'careersHero.scroll': 'ያስሱ',
		'careersCulture.sectionTag': 'ባህል // 01',
		'careersCulture.title1': 'ተራ የሆነውን',
		'careersCulture.title2': 'አንሰራም።',
		'careersCulture.description': 'ባህላችን ለተጋደሉ ተገንብቷል። ልሂቃን የሰው ሀይል ሰዎችን የሚፈታተን፣ የሚያሳድግ እና ጥብቅ ድጋፍ የሚሰጥ ምህዳር እንደሚፈልግ እናምናለን። እዚህ፣ የኦፕሬሽን ልቀት መሰረታዊ ደረጃ ነው።',
		'careersCulture.value1Title': 'አብዮታዊ ተጠያቂነት',
		'careersCulture.value1Desc': 'በእያንዳንዱ የማዕቀፍ ክፍል ውስጥ የባለቤትነት ስሜት።',
		'careersCulture.value2Title': 'ፈጠራ ኦፕሬሽኖች',
		'careersCulture.value2Desc': '። ግትር ችግሮችን በፈሳሽ አስተሳሰብ መፍታት።',
		'careersCulture.quote': 'አንድ ኩባንያ ሊያቀርበው ከሚችለው በጣም ማራኪ ነገር ለመጣስ ፈቃደኛ ያልሆነበት ደረጃ ነው።',
		'careersCulture.quoteAuthor': 'ዋና ሥራ አስፈጻሚ መመሪያ',
		'careersRoles.openRequisitions': 'ክፍት የስራ መደቦች',
		'careersRoles.title1': 'ወደ',
		'careersRoles.title2': 'መድረክ ግቡ።',
		'careersRoles.location': 'ቦታ',
		'careersRoles.type': 'አይነት',
		'careersStories.sectionTag': 'የስራ አስፈጻሚ አመለካከቶች // 03',
		'careersStories.quote': 'እኛ ሂደቶችን አንመራም። ለመላው አህጉር መዋቅራዊ እንቅስቃሴን እንፈጥራለን።',
		'careersStories.profileName': 'አማራ ኬ.',
		'careersStories.profileTitle': 'የተሰጥኦ ስርዓቶች ኃላፊ',
		'careersStories.profileAlt': 'መገለጫ',
		'careersStories.imageAlt': 'የስራ ቦታ ምህዳር',
		'careersBenefits.title1': 'ደረጃዎቹ',
		'careersBenefits.title2': 'ምንድን ናቸው።',
		'careersBenefits.benefit1.title': 'የስራ አስፈጻሚ ጎዳና',
		'careersBenefits.benefit1.desc': 'ጥብቅ አማካሪነት እና ከአለም አቀፍ ኦፕሬሽኖች ጋር ግልጽ ተጋላጭነት፣ ስራዎን በዓመታት ማፋጠን።',
		'careersBenefits.benefit2.title': 'ሉዓላዊ ተለዋዋጭነት',
		'careersBenefits.benefit2.desc': 'እኛ መገኘትን ሳይሆን ተፅእኖን እንለካለን። በንጹህ የኦፕሬሽን ውጤት ላይ የተዋቀሩ ፈሳሽ የርቀት ማዕቀፎች።',
		'careersBenefits.benefit3.title': 'የእውቀት ካፒታል',
		'careersBenefits.benefit3.desc': 'ቀጣይ ትምህርት፣ ሰርተፍኬቶች እና አለም አቀፍ የኢንተርፕራይዝ ኮንፈረንሶች ያልተገደበ በጀት።',
		'careersBenefits.benefit4.title': 'ሁሉን አቀፍ ሥነ ህንጻ',
		'careersBenefits.benefit4.desc': 'ለቤተሰብዎ የሚደርስ ከፍተኛ ጥራት ያለው የጤና እንክብካቤ፣ አጠቃላይ የደህንነት አበል እና የታዘዙ የእረፍት ጊዜዎች።',
		'careersProcess.title': 'የመግቢያ መንገዱ',
		'careersProcess.step1': 'ማመልከቻ',
		'careersProcess.step2': 'ማጣራት',
		'careersProcess.step3': 'ቃለ መጠይቅ',
		'careersProcess.step4': 'ምዘና',
		'careersProcess.step5': 'ቅናሽ',
		'careersProcess.step6': 'ማስጀመሪያ ስልጠና',
		'jobs.common.fullTime': 'የሙሉ ጊዜ',
		'jobs.vpOperations.title': 'የኢንተርፕራይዝ ኦፕሬሽኖች ምክትል ፕሬዝዳንት',
		'jobs.vpOperations.department': 'ሥራ አስፈጻሚ አመራር',
		'jobs.vpOperations.location': 'አዲስ አበባ፣ ኢትዮጵያ / ድብልቅ',
		'jobs.vpOperations.experience': 'ከ10+ ዓመታት በላይ የኢንተርፕራይዝ',
		'jobs.vpOperations.compensation': 'ከፍተኛ 5% ገበያ + ፍትሃዊነት',
		'jobs.vpOperations.window': 'ጥቅምት 15፣ 2026 ይዘጋል',
		'jobs.vpOperations.heroHeading': 'የወደፊቱን ይምሩ',
		'jobs.vpOperations.heroSubheading': 'የሰው ሀይል ፈጠራ።',
		'jobs.vpOperations.storyHeading': 'አነቃቂ',
		'jobs.vpOperations.storySubheading': 'የአመራር እድል።',
		'jobs.vpOperations.storyParagraph1':
			'ይህ የጥገና ሚና አይደለም። የኢንተርፕራይዝ ኦፕሬሽኖች ምክትል ፕሬዝዳንት እንደመሆንዎ መጠን፣ ዓለም አቀፍ የሰው ሀይል ስልቶቻችንን የሚያንቀሳቅሱ መሠረታዊ ስርዓቶችን ይመራሉ። ጠንካራ መሠረተ ልማት ይወርሳሉ እና በታዳጊ የአፍሪካ ገበያዎች ላይ ለማስፋፋት ከፍተኛ የኦፕሬሽን እውቀት እና ጥሬ ምኞትን በመጠቀም ይሰራሉ።',
		'jobs.vpOperations.storyParagraph2':
			'ካፒታል እንዴት እንደምናሰማራ፣ የተሰጥኦ ስነ-ምህዳሮችን እንደምንቀይር እና ባህላዊ የማማከር ገደቦችን እንደምናሸንፍ በቀጥታ ተጽዕኖ በማድረግ ለሥራ አስፈጻሚ ቦርዳችን ያልተጣራ ተጋላጭነት ይኖርዎታል። በአስርት ዓመታት የሚያስብ ግን በቀናት ውስጥ የሚፈጽም ሰው እንፈልጋለን።',
		'jobs.vpOperations.responsibility1': 'በ4 የተለያዩ ክልሎች ውስጥ ከ500+ ልሂቃን ሰራተኞች የሚደግፍ ሊሰፋ የሚችል የኦፕሬሽን ማዕቀፍ ይመሩ።',
		'jobs.vpOperations.responsibility2': 'በውስጣዊ የሰው ሀይል መሠረተ ልማት ላይ ያተኮረ ብዙ ሚሊዮን ዶላር የካፒታል ድልድል ስትራቴጂ በቀጥታ ያስተዳድሩ።',
		'jobs.vpOperations.responsibility3': 'የተፎካካሪዎችን የተሰጥኦ ስርዓቶች ለመቀልበስ እና የላቁ፣ ረብሻ አማራጮችን ለመገንባት ከዋና ሥራ አስፈጻሚ ጋር ይተባበሩ።',
		'jobs.vpOperations.responsibility4': 'የውስጥ ግንኙነታችንን ዲጂታል ትራንስፎርሜሽን ይምሩ፣ ከተበታተነ ሶፍትዌር ወደ አንድ የተዋሃደ 247HR የባለቤትነት ስርዓት በመሸጋገር።',
		'jobs.vpOperations.responsibility5': 'ጨካኝ ግን ደጋፊ የሆኑ የመካከለኛ አመራር መለኪያዎችን በማቋቋም ከፍተኛ አፈጻጸም ባህል ያዳብሩ።',
		'jobs.vpOperations.qual1.title': 'ከ10+ ዓመታት በላይ የኢንተርፕራይዝ ልምድ',
		'jobs.vpOperations.qual1.desc': 'በቲየር-1 ማማከር፣ ከፍተኛ እድገት ቴክኖሎጂ ወይም ዓለም አቀፍ የኮርፖሬት አካባቢዎች ውስጥ ሰፊ ኦፕሬሽኖችን በማስተዳደር የተረጋገጠ ሪከርድ።',
		'jobs.vpOperations.qual2.title': 'ስትራቴጂካዊ የፋይናንስ እውቀት',
		'jobs.vpOperations.qual2.desc': 'የትርፍ እና ኪሳራ አሠራር፣ የካፒታል ድልድል እና ለሰው ካፒታል ኢንቨስትመንት የROI ሞዴሊንግ ጥልቅ ግንዛቤ።',
		'jobs.vpOperations.qual3.title': 'የአፍሪካ ገበያ ቅልጥፍና',
		'jobs.vpOperations.qual3.desc': 'የፓን-አፍሪካ ቢዝነስ ስነ-ምህዳሮች፣ የቁጥጥር አካባቢዎች እና ከፍተኛ ዋጋ ያላቸው የተሰጥኦ አውታረመረቦች ስውር ግንዛቤ።',
		'jobs.vpOperations.qual4.title': 'ሉዓላዊ አፈጻጸም',
		'jobs.vpOperations.qual4.desc': 'የጨዋታ መመሪያ ሳያስፈልገው በጣም አሻሚ በሆኑ፣ ከፍተኛ ጫና ባለባቸው አካባቢዎች ውስጥ የመስራት ችሎታ። መመሪያውን የሚጽፉት እርስዎ ነዎት።',
		'jobs.workspaceArchitect.title': 'ከፍተኛ የስራ ቦታ አርክቴክት',
		'jobs.workspaceArchitect.department': 'የመሠረተ ልማት ዲዛይን',
		'jobs.workspaceArchitect.location': 'ላጎስ፣ ናይጄሪያ',
		'jobs.workspaceArchitect.experience': 'ከ7+ ዓመታት በላይ የቦታ ዲዛይን',
		'jobs.workspaceArchitect.compensation': 'ተወዳዳሪ + የአፈጻጸም ጉርሻ',
		'jobs.workspaceArchitect.window': 'ህዳር 1፣ 2026 ይዘጋል',
		'jobs.workspaceArchitect.heroHeading': 'ዋናውን ይንደፉ',
		'jobs.workspaceArchitect.heroSubheading': 'የኮርፖሬት ስነ-ምህዳሮች።',
		'jobs.workspaceArchitect.storyHeading': 'የቦታ',
		'jobs.workspaceArchitect.storySubheading': 'እውቀት የተካነ።',
		'jobs.workspaceArchitect.storyParagraph1':
			'አካላዊ እና ዲጂታል የስራ ቦታዎቻችን የማማከር ፍልስፍናችን መሠረት ናቸው። እንደ ከፍተኛ የስራ ቦታ አርክቴክት፣ የሚቀጥለው ትውልድ ቢሮ አካባቢዎችን በጽንሰ-ሀሳብ ደረጃ የማዘጋጀት እና የማስፈጸም ስራ አለብዎት።',
		'jobs.workspaceArchitect.storyParagraph2':
			'ከጊዜ ያለፈባቸው የኮርፖሬት አቀማመጦች ይላቀቃሉ። ዘመናዊውን አፍሪካ ኃይል የሚያንፀባርቁ እና ከፍተኛ ተግባራዊ መስፈርቶችን የሚያገለግሉ ደፋር፣ ብልህ እና ጥልቅ አይነት የቦታ ዲዛይኖች እንጠይቃለን። ስራዎ ልሂቃን አማካሪዎቻችን በዕለት ተዕለት ስራ እንዴት እንደሚሰሩ ይወስናል።',
		'jobs.workspaceArchitect.responsibility1': 'በምእራብ አፍሪካ ሶስት ዋና ዋና የክልል ዋና መሥሪያ ቤቶች ጅማሬን ከመጀመሪያ እስከ መጨረሻ ይምሩ እና ያስፈጽሙ።',
		'jobs.workspaceArchitect.responsibility2': 'የላቀ የኢንተርኔት ኦፍ ትህንግስ (IoT) እና የአካባቢ ቁጥጥር ስርዓቶችን እንከን የለሽ በሆነ መንገድ ወደ ብጁ አካላዊ መሠረተ ልማት ያዋህዱ።',
		'jobs.workspaceArchitect.responsibility3': 'ከፍተኛ ደረጃ ያላቸውን የአቅራቢ ግንኙነቶች ይደራደሩ እና ያስተዳድሩ፣ የማይበገር የቁሳቁስ ጥራት እና ትክክለኛ የጊዜ ሰሌዳዎችን ያረጋግጡ።',
		'jobs.workspaceArchitect.responsibility4': "የወደፊት ፈጣን-ማሰማሪያ ቢሮዎችን ደረጃውን የጠበቀ ለማድረግ የባለቤትነት '247HR የቦታ ማንነት መመሪያ' ያዘጋጁ።",
		'jobs.workspaceArchitect.qual1.title': 'ከ7+ ዓመታት በላይ የንግድ አርክቴክቸር',
		'jobs.workspaceArchitect.qual1.desc': 'በዘመናዊ መገልገያ ላይ ያተኮረ ሰፊ የቦታ ዲዛይን ወይም ከፍተኛ ደረጃ የኮርፖሬት ውስጣዊ ዲዛይን ዳራ።',
		'jobs.workspaceArchitect.qual2.title': 'የላቀ ሶፍትዌር እውቀት',
		'jobs.workspaceArchitect.qual2.desc': 'በ AutoCAD፣ Revit እና በማቅረቢያ ሞተሮች (V-Ray፣ Lumion) ላይ እውቀት፣ ከጠንካራ ግን የቅንጦት ውበት ስሜት ጋር።',
		'jobs.workspaceArchitect.qual3.title': 'ከፍተኛ በጀት አስተዳደር',
		'jobs.workspaceArchitect.qual3.desc': 'የዲዛይን ታማኝነት ሳይጣስ ወይም የጊዜ ገደቦች ሳይጠፉ ከ5 ሚሊዮን ብር በላይ የግንባታ በጀቶችን በማስተዳደር የተረጋገጠ ሪከርድ።',
		'jobs.workspaceArchitect.qual4.title': 'የአካባቢ ሥነ ልቦና',
		'jobs.workspaceArchitect.qual4.desc': 'አካላዊ አካባቢዎች ከፍተኛ ውርርድ ባለው ሙያዊ አፈጻጸም እና ትብብር ላይ እንዴት ተጽዕኖ እንደሚያሳድሩ ጥልቅ ግንዛቤ።',
		// Talent Analytics - AM Translations (Missing)
		'jobs.talentAnalytics.title': 'የተሰጥኦ ትንታኔ ኃላፊ',
		'jobs.talentAnalytics.department': 'የሰው ካፒታል ስትራቴጂ',
		'jobs.talentAnalytics.location': 'ርቀት / EMEA',
		'jobs.talentAnalytics.experience': 'ከ8+ ዓመታት በላይ የውሂብ ሳይንስ / የሰው ሀይል ክፍል',
		'jobs.talentAnalytics.compensation': 'ከፍተኛ 10% ገበያ + ፍትሃዊነት',
		'jobs.talentAnalytics.window': 'ተለዋዋጭ ቅበላ',
		'jobs.talentAnalytics.heroHeading': 'የሰውን',
		'jobs.talentAnalytics.heroSubheading': 'ችሎታ ይቁጠሩ።',
		'jobs.talentAnalytics.storyHeading': 'ትንበያ',
		'jobs.talentAnalytics.storySubheading': 'ተሰጥኦ ሞዴሊንግ።',
		'jobs.talentAnalytics.storyParagraph1':
			'ውሂብ የኛ የመጨረሻ አጠቃቀሚያ ነው። የተሰጥኦ ትንታኔ ኃላፊ ሙሉውን የሰው ካፒታል ውሂብ ቧንቧ መስመር ይይዛሉ፣ የተበታተኑ የባህሪ መለኪያዎችን ወደ ትክክለኛ እና ተግባራዊ ስልታዊ መመሪያዎች ለሥራ አስፈጻሚ ቡድን ይቀይራሉ።',
		'jobs.talentAnalytics.storyParagraph2':
			'መሠረታዊ የሰው ሀይል ክፍል ሪፖርት አንሰራም። መቃጠልን ለመተንበይ፣ በስነ-ልቦናዊ መገለጫዎች ላይ ተመስርተው የቡድን ስብስብን ለማመቻቸት እና የተሰጥኦ ማግኛ መስመሮቻችንን ትክክለኛ የROI መጠን ለማስላት ትንበያ ሞዴሎችን ይገነባሉ። የሰው ባህሪን ወደ ተወዳዳሪ የሂሳብ ጥቅሞች ይቀይራሉ።',
		'jobs.talentAnalytics.responsibility1': 'የላቁ ስታቲስቲካዊ ቴክኒኮችን እና ማሽን መማርን በመጠቀም ትንበያ ማጣራት እና የአፈጻጸም ሞዴሎችን ይገንቡ እና ያሰማሩ።',
		'jobs.talentAnalytics.responsibility2': 'የእውነተኛ ጊዜ ሥራ አስፈጻሚ ዳሽቦርዶችን ይንደፉ ይህም ወደ ዓለም አቀፍ የሰው ሀይል ጤና እና ተለዋዋጭነት ያልተጣራ ታይነት ይሰጣል።',
		'jobs.talentAnalytics.responsibility3': 'አድሏዊነትን ለማስወገድ እና ያልተመጣጠነ ተጽእኖን ለመሸለም የአፈጻጸም ግምገማ አልጎሪዝሞቻችንን ይመርምሩ እና ሙሉ በሙሉ ያሻሽሉ።',
		'jobs.talentAnalytics.responsibility4': 'የመዋቅር መልሶ ማደራጀት የፋይናንስ ተጽእኖ ለመቅረጽ ከኢንተርፕራይዝ ኦፕሬሽኖች ምክትል ፕሬዝዳንት ጋር በቀጥታ ይተባበሩ።',
		'jobs.talentAnalytics.qual1.title': 'ከ8+ ዓመታት በላይ የውሂብ ሳይንስ',
		'jobs.talentAnalytics.qual1.desc': 'የውሂብ ሳይንስ እና የሰው ካፒታልን ማገናኘት፣ በተለይም በከፍተኛ እድገት ቴክኖሎጂ ወይም ልሂቃን ማማከር ውስጥ።',
		'jobs.talentAnalytics.qual2.title': 'ቴክኒካዊ የበላይነት',
		'jobs.talentAnalytics.qual2.desc': 'በ Python፣ R፣ SQL እና በላቁ ምስላዊ መድረኮች (Tableau፣ PowerBI) ላይ የባለሙያ-ደረጃ ብቃት።',
		'jobs.talentAnalytics.qual3.title': 'ሥራ አስፈጻሚ ተረት አቀራረብ',
		'jobs.talentAnalytics.qual3.desc': 'እጅግ ውስብስብ የሆኑ ስታቲስቲካዊ ግኝቶችን ወደ ግልጽ፣ የማይካድ የንግድ ጉዳዮች የመተርጎም ችሎታ።',
		'jobs.talentAnalytics.qual4.title': 'ትንታኔያዊ ጥርጣሬ',
		'jobs.talentAnalytics.qual4.desc': 'በባህላዊ የሰው ሀይል ክፍል መለኪያዎች ላይ ጥልቅ ጥርጣሬ እና ስኬትን በትክክል የሚወስነውን ለመለካት የማያቋርጥ ግፊት።',
		'jobs.complianceDirector.title': 'የታዛዥነት ስርዓቶች ዳይሬክተር',
		'jobs.complianceDirector.department': 'ስጋት እና አስተዳደር',
		'jobs.complianceDirector.location': 'ጆሃንስበርግ፣ ደቡብ አፍሪካ',
		'jobs.complianceDirector.experience': 'ከ12+ ዓመታት በላይ አስተዳደር',
		'jobs.complianceDirector.compensation': 'ከፍተኛ ተወዳዳሪ',
		'jobs.complianceDirector.window': 'ታህሳስ 1፣ 2026 ይዘጋል',
		'jobs.complianceDirector.heroHeading': 'እድገታችንን',
		'jobs.complianceDirector.heroSubheading': 'ይከላከሉ።',
		'jobs.complianceDirector.storyHeading': 'የተመሸገ',
		'jobs.complianceDirector.storySubheading': 'አስተዳደር።',
		'jobs.complianceDirector.storyParagraph1':
			'በተለያዩ የአፍሪካ ገበያዎች መስፋፋት እጅግ ውስብስብ የሆነ የቁጥጥር ማዕቀፎችን መዳሰስ ይጠይቃል። የታዛዥነት ስርዓቶች ዳይሬክተር ኦፕሬሽኖቻችን ህልውናን አደጋ ላይ ሳይጥሉ በፍጥነት እንዲንቀሳቀሱ የሚያስችል ጋሻ ነው።',
		'jobs.complianceDirector.storyParagraph2':
			'ለደንቦች ምላሽ ብቻ አይሰጡም፤ ይጠባበቋቸዋል። ሚናዎ በዕለት ተዕለት ኦፕሬሽኖቻችን ውስጥ እንከን የለሽ በሆነ መንገድ የሚዋሃድ አውቶማቲክ፣ የማይወጋ የታዛዥነት መሠረተ ልማት መገንባት ነው። የቁጥጥር ተገዢነትን ከቢሮክራሲያዊ መሰናክል ወደ ዝምታ፣ እንከን የለሽ ዋስትና ይቀይሩታል።',
		'jobs.complianceDirector.responsibility1': 'የሰራተኛ ህጎችን፣ የውሂብ ግላዊነት (GDPR/POPIA) እና የፋይናንስ ሪፖርት አቀራረብ ደረጃዎችን የሚሸፍን የፓን-አፍሪካ ታዛዥነት ሞተር ይመሩ።',
		'jobs.complianceDirector.responsibility2': 'ድንበር ተሻጋሪ የውስጥ ኦዲቶችን ይምሩ እና ከከፍተኛ ደረጃ የውጭ የህግ አማካሪዎች እና ተቆጣጣሪዎች ጋር ዋና አገናኝ ሆነው ያገለግሉ።',
		'jobs.complianceDirector.responsibility3': 'ልዩ ሶፍትዌርን በቀጥታ ወደ የሰው ሀይል ክፍል እና ፋይናንስ ቁልሎቻችን በማዋሃድ 80% መደበኛ የታዛዥነት ቼኮችን አውቶማቲክ ያድርጉ።',
		'jobs.complianceDirector.responsibility4': 'ለቁጥጥር ለውጦች ፈጣን ምላሽ ፕሮቶኮሎችን ያዘጋጁ፣ ተለዋዋጭ በሆኑ ግዛቶች ውስጥ ዜሮ የኦፕሬሽን መቀነስ ያረጋግጡ።',
		'jobs.complianceDirector.qual1.title': 'ከ12+ ዓመታት በላይ የኮርፖሬት አስተዳደር',
		'jobs.complianceDirector.qual1.desc': 'በአደጋ አስተዳደር ወይም በኮርፖሬት ህግ ውስጥ ሰፊ ዳራ፣ በበርካታ ግዛቶች ታዛዥነት ላይ ከፍተኛ ትኩረት ያደርጋል።',
		'jobs.complianceDirector.qual2.title': 'የፓን-አፍሪካ ህጋዊ ማዕቀፎች',
		'jobs.complianceDirector.qual2.desc': 'በዋና ዋና የአፍሪካ ማዕከላት (ደቡብ አፍሪካ፣ ኬንያ፣ ናይጄሪያ) ውስጥ የሰራተኛ ህጎች እና የውሂብ ግላዊነት ደንቦች ጥልቅ፣ በውጊያ የተረጋገጠ እውቀት።',
		'jobs.complianceDirector.qual3.title': 'ዲጂታል ትራንስፎርሜሽን አመራር',
		'jobs.complianceDirector.qual3.desc': 'በህግ ወይም በታዛዥነት ክፍሎች ውስጥ ዲጂታል ትራንስፎርሜሽን በመምራት ከወረቀት ወደ አውቶማቲክ ስርዓቶች በመሸጋገር ልምድ።',
		'jobs.complianceDirector.qual4.title': 'የማይናወጥ የአደጋ ምዘና',
		'jobs.complianceDirector.qual4.desc': 'በከፍተኛ የኦፕሬሽን ጫና ውስጥ ትክክለኛ፣ ከፍተኛ ውርርድ ያላቸውን የአደጋ ምዘናዎች የመወሰን ችሎታ ያለው የማይናወጥ ባህሪ።',
		'careersWorkspace.sectionTag': 'የኦፕሬሽን ስነ-ምህዳር // 05',
		'careersWorkspace.title': 'የምኞት \n ሥነ ህንጻ።',
		'careersWorkspace.label1': 'ዋና መሥሪያ ቤት / የትብብር ማዕከል',
		'careersWorkspace.label2': 'ሥራ አስፈጻሚ ማረፊያ ክፍል',
		'careersWorkspace.imageAlt1': 'የቅንጦት የስራ ቦታ',
		'careersWorkspace.imageAlt2': 'ማረፊያ ክፍል',
		'careersWorkspace.description':
			'ሰራተኞችን ለማስተናገድ ብቻ ሳይሆን ልሂቃን አፈጻጸምን በአካል ለማነቃቃት የተነደፉ ቦታዎች። የ247HR የስራ ቦታ እንደ የቅንጦት ንብረት ሆኖ ያገለግላል፣ ከፍተኛ ደረጃ ትኩረትን እና የትብብር ውህደትን ያጎለብታል።',
		'careersCTA.backgroundAlt': 'ረቂቅ ሲኒማቲክ',
		'careersCTA.title1': 'የወደፊት ጊዜን ከሚገነባው የሰው ሀይል ጋር ይቀላቀሉ',
		'careersCTA.title2': 'የኢንተርፕራይዝ ኦፕሬሽኖች።',
		'careersCTA.button': 'ማመልከቻ ይጀምሩ',
		'aboutHero.tagline': 'የወደፊቱ ኦፕሬቲንግ ሲስተም',
		'aboutHero.title1': 'ከአፍሪካ መሪ',
		'aboutHero.title2': 'ኢንተርፕራይዞች በስተጀርባ',
		'aboutHero.title3': 'ያለውን የሰው ሀይል እናንቀሳቅሳለን',
		'aboutHero.description': 'እኛ ዘመናዊ የሰው ሀይል ስነ-ምህዳሮች የኦፕሬሽን የጀርባ አጥንት ነን፣ ለፈጣን የገበያ ዘልቆ ሊሰፋ የሚችል የሰው ካፒታል መሠረተ ልማት እንመራለን።',
		'aboutHero.buttonExplore': 'አገልግሎቶችን ያስሱ',
		'aboutHero.buttonWorkWithUs': 'ከእኛ ጋር ይስሩ',
		'aboutHero.imageAlt': 'የኢንተርፕራይዝ አካባቢ',
		'aboutHero.metric1Title': 'የኦፕሬሽን ፍጥነት',
		'aboutHero.metric1Value': '+24% በወር',
		'aboutHero.metric2Title': 'ንቁ ማሰማራቶች',
		'aboutHero.metric2Value': '14 ግዛቶች',
		'aboutHero.metric2Extra': '+1.2ሺ',
		'aboutStory.mainImageAlt': 'የ247HR ቡድን ኦፕሬሽኖች',
		'aboutStory.overlayImageAlt': 'ሙያዊ ስራ',
		'aboutStory.title1': 'አህጉራዊውን',
		'aboutStory.title2': 'ሞተር በሥነ ህንጻ መምራት',
		'aboutStory.section1Title': 'መሠረታዊው ራዕይ',
		'aboutStory.section1Desc':
			'በአንድ ቀጥተኛ መመሪያ ተመስርቷል፡ የፓን-አፍሪካ ኢንተርፕራይዝ መስፋፋትን መሰናክሎች ለማስወገድ። ከፍተኛ እድገት ያላቸው ኩባንያዎች በገበያ ፍላጎት ሳይሆን በተበታተነ የሰው ካፒታል መሠረተ ልማት እንደሚደናቀፉ አይተናል።',
		'aboutStory.section2Title': 'የኦፕሬሽን እድገት',
		'aboutStory.section2Desc': 'እንደ ፕሪሚየም ሪክሩትመንት አማካሪነት የጀመረው ወደ አጠቃላይ የሰው ሀይል ኦፕሬቲንግ ሲስተም በፍጥነት ተስፋፍቷል። አሁን ከባለብዙ ግዛት የደመወዝ ክፍያ እስከ ሥራ አስፈጻሚ ተሰጥኦ ድረስ ሁሉንም ነገር እንመራለን።',
		'aboutStory.quote': '"የእኛ ተልዕኮ ሰው ማቅረብ ብቻ አይደለም። ንግዶች ያለምንም ፍርሃት እንዲስፋፉ የሚያስችል ጠንካራ የኦፕሬሽን ሥነ ህንጻ መገንባት ነው።"',
		'aboutMission.missionLabel': 'ተልዕኳችን',
		'aboutMission.missionTitle1': 'ለአፍሪካ ከፍተኛ እድገት ኩባንያዎች',
		'aboutMission.missionTitle2': 'ጠንካራ',
		'aboutMission.missionTitle3': 'የሰው ካፒታል ስርዓቶችን መምራት',
		'aboutMission.missionDesc':
			'የኦፕሬሽን መሰናክሎችን የሚያስወግድ ዓለም አቀፍ ደረጃ ያለው የሰው ሀይል መሠረተ ልማት እናሰማራለን፣ ደንበኞቻችን በገበያ በላይነት ላይ ብቻ እንዲያተኩሩ እናረጋግጣለን እኛ ደግሞ የተሰጥኦን፣ የታዛዥነት እና የልኬት ውስብስብነት እንይዛለን።',
		'aboutMission.visionLabel': 'ራእያችን',
		'aboutMission.visionTitle1': 'ለአህጉራዊ የሰው ሀይል አስተዳደር',
		'aboutMission.visionTitle2': 'ነባራዊ ኦፕሬቲንግ ሲስተም',
		'aboutMission.visionTitle3': 'መሆን',
		'aboutMission.visionDesc': 'ድንበር አልባ የኮርፖሬት መልክዓ ምድርን እንገምታለን፣ በአፍሪካ ግዛቶች ውስጥ ተሰጥኦን ማሰማራት ዲጂታል ክፍያ እንደማካሄድ ሁሉ እንከን የለሽ፣ ግልጽ እና ደህንነቱ የተጠበቀ ነው።',
		'aboutValues.title1': 'የምንሰራበት',
		'aboutValues.title2': 'ኮድ',
		'aboutValues.description': 'ዋና እሴቶቻችን በግድግዳ ላይ የሚለጠፍ ፖስተር አይደሉም፤ እኛ በምንፈጽመው እያንዳንዱ ማሰማራት፣ ቅጥር እና ስትራቴጂ ላይ የሚተዳደሩ ጥብቅ የኦፕሬሽን ፕሮቶኮሎች ናቸው።',
		'aboutValues.value1.title': 'የኦፕሬሽን ልቀት',
		'aboutValues.value1.desc': 'ከታዛዥነት እስከ የደመወዝ ክፍያ አፈጻጸም ድረስ በእያንዳንዱ ሂደት ውስጥ ትክክለኛነት።',
		'aboutValues.value2.title': 'የተሰጥኦ እውቀት',
		'aboutValues.value2.desc': 'ግምትን በስትራቴጂካዊ ግዥ በመተካት በውሂብ የሚመራ ቅጥር።',
		'aboutValues.value3.title': 'ፍጥነት',
		'aboutValues.value3.desc': 'በማሰማራት እና በኦፕሬሽን መስፋፋት ላይ የማይወዳደር ፍጥነት።',
		'aboutValues.value4.title': 'የኢንተርፕራይዝ አስተማማኝነት',
		'aboutValues.value4.desc': 'በጣም አስፈላጊ በሆነ ጊዜ ፈጽሞ የማይሳካ ጠንካራ መሠረተ ልማት።',
		'aboutValues.value5.title': 'የሰው ሀይል ፈጠራ',
		'aboutValues.value5.desc': 'የሰው ካፒታል ቴክኖሎጂ ድንበሮችን ያለማቋረጥ መግፋት።',
		'aboutValues.value6.title': 'ታማኝነት',
		'aboutValues.value6.desc': 'ፍጹም ግልጽነት እና የማያፈነግጥ የስነምግባር ደረጃዎች።',
		'aboutTeam.title1': 'ትእዛዝ እና',
		'aboutTeam.title2': 'ቁጥጥር',
		'aboutTeam.description': 'በአህጉራዊ መስፋፋት ውስብስብ ሁኔታዎች ውስጥ የተፈጠረ የአመራር ቡድን። አስርት ዓመታትን ያስቆጠረ የብዝሃ ግዛት የኢንተርፕራይዝ ልምድ እናመጣለን።',
		'aboutTeam.button': 'ሙሉ አመራር ይመልከቱ',
		'aboutTeam.leader1.name': 'ዴቪድ ኦ. አላቢ',
		'aboutTeam.leader1.role': 'ዋና ሥራ አስፈጻሚ ኦፊሰር',
		'aboutTeam.leader2.name': 'አይሻ ኤን. መንሳህ',
		'aboutTeam.leader2.role': 'የተሰጥኦ እውቀት ኃላፊ',
		'aboutTeam.leader3.name': 'ሳሙኤል ኬ. ተስፋዬ',
		'aboutTeam.leader3.role': 'የኢንተርፕራይዝ ኦፕሬሽኖች ምክትል ፕሬዝዳንት',
		'aboutMetrics.title1': 'የተፅእኖአችን',
		'aboutMetrics.title2': 'ልኬት',
		'aboutMetrics.description': 'እኛ በግምት አንሰራም። በሚለካ፣ ሊሰፋ በሚችል የኢንተርፕራይዝ አፈጻጸም እንሰራለን። የእኛ መሠረተ ልማት በአህጉሪቱ በጣም ምኞተኛ ከሆኑ ኩባንያዎች የሰው ሀይል ፍላጎቶችን ይደግፋል።',
		'aboutMetrics.metric1.label': 'የኢንተርፕራይዝ ደንበኞች',
		'aboutMetrics.metric1.desc': 'በ14 ንቁ ግዛቶች ውስጥ',
		'aboutMetrics.metric2.label': 'የሰው ሀይል ምደባዎች',
		'aboutMetrics.metric2.desc': 'በየዓመቱ የሚደራጅ ተሰጥኦ',
		'aboutMetrics.metric3.label': 'የደመወዝ ክፍያ ስራዎች',
		'aboutMetrics.metric3.desc': 'በእኛ ሥነ ህንጻ የሚካሄድ',
		'aboutMetrics.metric4.label': 'የተሰጥኦ ስኬት መጠን',
		'aboutMetrics.metric4.desc': 'የሥራ አስፈጻሚ እና ቴክኒካል ማቆየት',
		'aboutCulture.title1': 'የማይበገር አፈጻጸም',
		'aboutCulture.title2': 'ባህል',
		'aboutCulture.description': 'ከቴክኖሎጂያችን በስተጀርባ የሰው ካፒታል የመጨረሻው ተወዳዳሪ ጥቅም ነው ብለው የሚያምኑ ኦፕሬተሮች ቡድን ይገኛል።',
		'aboutCulture.quote': '"ተሰጥኦ ብቻ አንቀጥርም። ቡድኖችን በሥነ ህንጻ እንመራለን።"',
		'aboutCulture.quoteAuthor': 'የውስጥ ኦፕሬሽኖች ኃላፊ',
		'aboutCulture.imageAlt1': 'የቡድን ትብብር',
		'aboutCulture.imageAlt2': 'የአመራር ጊዜ',
		'aboutCulture.imageAlt3': 'ዘመናዊ ቢሮ ኮርፖሬት ህንጻ',
		'aboutCTA.badge': 'ቀጣዩ እርምጃ',
		'aboutCTA.title1': 'የወደፊቱን የሰው ሀይል',
		'aboutCTA.title2': 'ኦፕሬሽኖች',
		'aboutCTA.title3': 'ከ247HR ጋር ይገንቡ',
		'aboutCTA.buttonPrimary': 'ለውጥዎን ይጀምሩ',
		'aboutCTA.buttonSecondary': 'ከአመራር ጋር ይነጋገሩ',
		// Hero Section
		'contact.heroBadge': 'ዓለም አቀፍ ግንኙነቶች',
		'contact.heroTitle1': 'የበለጠ ብልህ',
		'contact.heroTitle2': 'የሰው ሀይል ስርዓቶችን',
		'contact.heroTitle3': 'አንሰራለን።',
		'contact.heroDescription': 'ከወደፊቱ የኢንተርፕራይዝ የሰው ሀይል መፍትሄዎች ጋር ይገናኙ። እኛ መደበኛ ድጋፍ አንሰጥም—ከፍተኛ የኦፕሬሽን ማማከር እናቀርባለን።',

		// Form Section
		'contact.formTitle': 'ውይይት ይጀምሩ',
		'contact.fullNamePlaceholder': 'ሙሉ ስም',
		'contact.companyNamePlaceholder': 'የኩባንያ ስም',
		'contact.emailPlaceholder': 'ኢሜይል አድራሻ',
		'contact.phonePlaceholder': 'ስልክ ቁጥር',
		'contact.serviceInterestPlaceholder': 'ፍላጎት ያለው አገልግሎት',
		'contact.serviceOption1': 'ሥራ አስፈጻሚ ፍለጋ',
		'contact.serviceOption2': 'የሰው ሀይል መሠረተ ልማት',
		'contact.serviceOption3': 'ስጋት እና ታዛዥነት',
		'contact.serviceOption4': 'ተሰጥኦ ትንታኔ',
		'contact.messagePlaceholder': 'መልዕክት',
		'contact.submitButton': 'ፕሮቶኮል አስተላልፍ',

		// Contact Information
		'contact.hqLabel': 'ዓለም አቀፍ ዋና መሥሪያ ቤት',
		'contact.hqAddress1': 'ዘ ኤክስቼንጅ ታወር፣',
		'contact.hqAddress2': 'አዲስ አበባ፣ ኢትዮጵያ',
		'contact.hqAddress3': ' ',
		'contact.emailLabel': 'ቀጥተኛ መስመር',
		'contact.emailAddress': 'executive@247consulting.com',
		'contact.phoneLabel': 'ኦፕሬሽን ማዕከል',
		'contact.phoneNumber': '+254 700 247 000',
		'contact.coverageLabel': 'ዓለም አቀፍ ሽፋን',
		'contact.coverageLine1': '24/7 የኢንተርፕራይዝ ድጋፍ',
		'contact.coverageLine2': 'GMT+3 ዋና ኦፕሬሽኖች',

		// Map Section
		'contact.mapHubName': 'ናይሮቢ ማዕከል',
		'contact.mapCoordinates': '1.2921° ደቡብ, 36.8219° ምስራቅ',

		// Final CTA Section
		'contact.finalBadge': 'የሥራ አስፈጻሚ የቀን መቁጠሪያ ክፍት ነው',
		'contact.finalTitle1': 'የወደፊቱን የሰው ሀይል',
		'contact.finalTitle2': 'ኦፕሬሽኖች መገንባት ይጀምሩ',
		'contact.finalButton': 'የስትራቴጂ ክፍለ ጊዜ ይያዙ',

		// Footer CTA Section
		'footer.ctaTitle1': 'የኢንተርፕራይዝ የሰው ሀይል',
		'footer.ctaTitle2': 'ከፍተኛ ደረጃ',
		'footer.ctaButton': 'ውይይት ይጀምሩ',
		'footer.newsletterText': 'ስለ ፓን-አፍሪካ የሰው ሀይል ሥነ ህንጻ ልዩ እውቀት ለማግኘት ይመዝገቡ።',
		'footer.newsletterPlaceholder': 'ሥራ አስፈጻሚ ኢሜይል',

		// Footer HQ Section
		'footer.hqDescription': 'ዓለም አቀፍ ዋና መሥሪያ ቤት፡ ናይሮቢ፣ ኬንያ። በታዳጊ የኢንተርፕራይዝ ገበያዎች ላይ ልሂቃን የሰው ሀይል መሠረተ ልማት ማሰማራት።',

		// Footer Column Titles
		'footer.intelligenceTitle': 'እውቀት',
		'footer.infrastructureTitle': 'መሠረተ ልማት',
		'footer.networkTitle': 'አውታረመረብ',

		// Intelligence Links
		'footer.aboutBoard': 'ስለ ቦርድ',
		'footer.leadership': 'አመራር',
		'footer.globalNetwork': 'ዓለም አቀፍ አውታረመረብ',
		'footer.esgImpact': 'ESG ተጽእኖ',

		// Infrastructure Links
		'footer.executiveSearch': 'ሥራ አስፈጻሚ ፍለጋ',
		'footer.workforceOperations': 'የሰው ሀይል ኦፕሬሽኖች',
		'footer.talentAnalytics': 'ተሰጥኦ ትንታኔ',
		'footer.riskCompliance': 'ስጋት እና ታዛዥነት',

		// Network Links
		'footer.openRequisitions': 'ክፍት የስራ መደቦች',
		'footer.lifeAt247hr': 'በ247HR ህይወት',
		'footer.globalLocations': 'ዓለም አቀፍ አካባቢዎች',
		'footer.pressMedia': 'ፕሬስ እና ሚዲያ',

		// Legal Links
		'footer.privacyProtocol': 'የግላዊነት ፕሮቶኮል',
		'footer.termsOfService': 'የአገልግሎት ውሎች',
		'footer.cookieArchitecture': 'የኩኪ ሥነ ህንጻ',
	},
};

interface LanguageContextType {
	language: Language;
	toggleLanguage: () => void;
	t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
	const [language, setLanguage] = useState<Language>('EN');

	useEffect(() => {
		const savedLang = localStorage.getItem('language') as Language;
		if (savedLang === 'EN' || savedLang === 'AM') {
			setLanguage(savedLang);
		}
	}, []);

	const toggleLanguage = () => {
		const newLang = language === 'EN' ? 'AM' : 'EN';
		setLanguage(newLang);
		localStorage.setItem('language', newLang);
	};

	const t = (key: string, fallback?: string) => {
		return translations[language][key] || fallback || key;
	};

	return <LanguageContext.Provider value={{ language, toggleLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
	const context = useContext(LanguageContext);
	if (context === undefined) {
		throw new Error('useLanguage must be used within a LanguageProvider');
	}
	return context;
}
